### ISSUE TITLE
Unable to open on Windows 10

### ISSUE THREAD

**Issue by 1024mb** [axcore/tartube#11]
Just installed tartube on Win 10 x64 and when opening the program nothing happens. Cmd window is shown for 1ms and then nothing, tried running command from cmd window and still nothing, no error, nor nothing.
I've UAC disabled, AV disabled.

When running hello_world bat I got this from mingw:

/etc/post-install/01-devices.post: line 56: chmod: command not found
/etc/post-install/01-devices.post: line 85: chmod: command not found
/etc/post-install/01-devices.post: line 90: /usr/bin/test: No such file or directory
/etc/post-install/01-devices.post: line 90: ln: command not found
/etc/post-install/01-devices.post: line 91: /usr/bin/test: No such file or directory
/etc/post-install/01-devices.post: line 91: ln: command not found
/etc/post-install/01-devices.post: line 92: /usr/bin/test: No such file or directory
/etc/post-install/01-devices.post: line 92: ln: command not found
/etc/post-install/01-devices.post: line 93: /usr/bin/test: No such file or directory
/etc/post-install/01-devices.post: line 93: ln: command not found
/etc/post-install/03-mtab.post: line 5: ln: command not found
/etc/post-install/05-home-dir.post: line 4: exec: id: not found
/etc/post-install/05-home-dir.post: line 224: mkdir: command not found
/home/angel could not be created.
Setting HOME to /tmp.
/etc/profile: line 128: /usr/bin/hostname: No such file or directory
/etc/profile.d/lang.sh: line 19: /usr/bin/locale: No such file or directory
/etc/profile.d/tzset.sh: line 22: /usr/bin/tzset: No such file or directory
/home/user/tartube/hello_world_mswin.sh: line 4: cd: tartube: No such file or directory
C:\Programas\Tartube\msys64\mingw64\bin\python3.exe: can't open file 'hello_world.py': [Errno 2] No such file or directory
/bin/env: Exit 2.

**Comment by axcore** [comment]
Hi 1024mb, I released Tartube v1.0.0 today, which might fix your problem.

If it doesn't work, please click the Start menu, select Tartube > Gtk graphics test, and tell me the error message you see

**Comment by d00gatr0n** [comment]
I just tested v1.0.0, I'm getting the same results as previous version, nothing happens when its launched...

Output from Gtk Graphics test is:

/home/user/tartube/hello_world_mswin.sh: line 4: cd: tartube: No such file or directory
C:\Users\[username]\AppData\Local\Tartube\msys64\mingw64\bin\python3.exe: can't open file 'hello_world.py': [Errno 2] No such file or directory
/bin/env: Exit 2.

**Comment by axcore** [comment]
Several people have reported a similar problem, but I have not been able to reproduce it on any machine.

The next steps depend on how much time you're willing to spend poking around. The main page ( https://github.com/axcore/tartube ) describes how to perform a manual installation; you could try that, if you have time for it.

**Comment by d00gatr0n** [comment]
Thanks, got it working by going through the manual instructions.

**Comment by 1024mb** [comment]
Hi, @axcore, version 1.0 didn't solve this. Manual installation using v1.0 source works great. Would have been nice to solve the installer issue but in the meantime manual method is working well. Thanks.

**Comment by 1024mb** [comment]
So, I could launch Tartube without problems but when I try to download a YouTube video I got these errors:

![python3_2019-08-01_01-05-32](https://user-images.githubusercontent.com/9301204/62269425-a8658e80-b3f8-11e9-893d-b0baa1070dfa.png)

**Comment by axcore** [comment]
@1024mb regarding those error messages, the first thing to do is to check that youtube-dl is installed and up to date. ('Unable to download webpage' errors are usually caused by an old youtube-dl version).

To update youtube-dl, start Tartube and click Operations > Update youtube-dl. If successful, this will update (or install) version 2019.7.30.

If that doesn't work, you can paste the URL of one of the videos that won't download, and I will try to download the same video.

**Comment by axcore** [comment]
>/media/veracrypt2/Local11/Code/tartube_WATCH/DATA

@1024mb, the installer issue can be solved, but only by someone who has the time to do some poking around.

Briefly, the manual installation creates 2GB of data. When compressed, that is 600MB. When I create the installer, I strip away everything that looks irrelevant, which leaves me with a 90MB installer. This installer works for most people, but there is something missing that is causing the errors you are getting.

**Comment by 1024mb** [comment]
Thanks for the help. Tried updating youtube-dl but still nada. I got the same messages.
It happens with every video I add, here is one:
https://www.youtube.com/watch?v=Vl0mQaE0sGs

It seems to be some error with the certificates, is there any command to disable SSL verification?

Git command doesn't work
`git config --global http.sslVerify false`

**Comment by axcore** [comment]
I was able to download that video without problems. You can try this youtube-dl option:

--no-check-certificate

Copy it into the box **Edit > General download options... > Extra youtube-dl command line options**

If that doesn't work, you can try running youtube-dl from the command line. Assuming a manual Tartube installation, open the MINGW64 terminal (C:\\msys64\\mingw64.exe) and type

youtube-dl https://www.youtube.com/watch?v=Vl0mQaE0sGs

**Comment by chrisblah** [comment]
I'm having the exact same issue as the OP. I went through and did the manual instructions and it fails in the last step. 

$ python3 tartube
-bash: python3: command not found

I assume that python3 was installed in one of the first pacman commands.

**Comment by axcore** [comment]
First make sure your Windows installation is 64-bit, not 32-bit. Then you could try typing this again:

**pacman -S mingw-w64-x86_64-python3**

**Comment by 1024mb** [comment]
@axcore Thanks for the help, tried the command you said and it worked to some point because after it I got these new errors:
![python3_2019-08-03_02-59-48](https://user-images.githubusercontent.com/9301204/62409438-c4099a00-b59c-11e9-8b35-48465d53f988.png)

In the end I had to add all of this, otherwise I couldn't even check the videos.

`--no-check-certificate -f best`

For some reason the selected formats I set in the app settings aren't used.
With both commands is now working fine. Videos download well.

Something I want to ask you -and I don't know if I better open an issue or if it's okay to put it here- is that please add a button or a contextual menu to 1. Play the downloaded videos and 2. Delete them from disk, all of this from the "Progress" tab (in addition to what it is in the "Video" tab).
Also an option to disable downloading into sub-folders and directly download to the folder one selects in Tartube's settings, I think it should be explicit in the app settings so we can directly disable it.

Thanks for all your help!

**Comment by axcore** [comment]
Hi 1024mb, sorry for the holiday delay,

The 'child process exited' error is nothing to worry about. You can disable it in **Edit > System preferences**. I'm not sure what is causing the 248 errors. If you thought it was worth the effort, you could tell me exactly which changes you have made in **Edit > General download options**, and then I could try to reproduce them.

About ffmpeg, installing it is not easy (the general process is described https://trac.ffmpeg.org/wiki/CompilationGuide/MinGW ). I will look into it, and see if ffmpeg can be added to the Tartube installer.

About your requests:

1. Play the downloaded videos - ok
2. Delete them from disk - you mean, play them and then delete them?  (Auto-delete every watched video?)
3. Disable download into sub-folders - you mean, when downloading channels and playlists, store all the videos in a designated folder, rather than creating a folder for each channel and playlist?
4. The 'Add Videos' video has been rewritten to make that quicker
